In [8]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("/Users/minsu/Desktop/diabetes.csv")
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [64]:
X = df.drop("Outcome", axis=1)
X.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [66]:
y = df["Outcome"]
y.value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [68]:
from sklearn.model_selection import train_test_split

In [77]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [79]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

# ML SVC Model

In [92]:
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(X_train, y_train)

pred_svm = clf_svm.predict(X_test)
svm_accuracy = accuracy_score(y_test, pred_svm)

In [111]:
print("--- SVM Classification ---")
print(f"SVM Accuracy: {svm_accuracy:.2f}")
print(confusion_matrix(y_test, pred_svm))

--- SVM Classification ---
SVM Accuracy: 0.77
[[119  11]
 [ 33  29]]


# ML LR Classification Model

In [114]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(max_iter=200)
lr_model.fit(X_train, y_train)

y_pred_lr = lr_model.predict(X_test)
lr_accuracy = accuracy_score(y_test, lr_pred)

In [116]:
print("--- LR Classification ---")
print(f"LR Accuracy {lr_accuracy:.2f}")
print(confusion_matrix(y_test, y_pred_lr))

--- LR Classification ---
LR Accuracy 0.80
[[117  13]
 [ 26  36]]


# ML RF Classification Model

In [136]:
from sklearn.ensemble import RandomForestClassifier

clf_rf = RandomForestClassifier(random_state=42)
clf_rf.fit(X_train, y_train)

y_pred_rf = clf_rf.predict(X_test)
rf_accuracy = accuracy_score(y_test, y_pred_rf)

In [138]:
print("--- RF Classification ----")
print(f"RF Accuracy: {rf_accuracy:.2f}")
print(confusion_matrix(y_test, y_pred_rf))

--- RF Classification ----
RF Accuracy: 0.82
[[117  13]
 [ 21  41]]


# ML Deision Tree

In [153]:
from sklearn.tree import DecisionTreeClassifier

clt_dt = DecisionTreeClassifier(random_state=0)
clt_dt.fit(X_train, y_train)

y_pred_dt = clt_dt.predict(X_test)
dt_accuracy = accuracy_score(y_test, y_pred_dt)

print("--- DT Classification ---")
print(f"DT Accuracy: {dt_accuracy:.2f}")
print(confusion_matrix(y_test, y_pred_dt))

--- DT Classification ---
DT Accuracy: 0.72
[[102  28]
 [ 26  36]]


# ML KNN Classification

In [158]:
from sklearn.neighbors import KNeighborsClassifier

clf_knn = KNeighborsClassifier()
clf_knn.fit(X_train, y_train)

y_pred_knn = clf_knn.predict(X_test)
knn_accuracy = accuracy_score(y_test, y_pred_knn)

In [162]:
print("--- KNN Classification ---")
print(f"KNN Accuracy: {knn_accuracy:.2f}")
print(confusion_matrix(y_test, y_pred_knn))

--- KNN Classification ---
KNN Accuracy: 0.76
[[109  21]
 [ 26  36]]


In [166]:
print("--- Classification Result ---")
print(f"SVM Accuracy: {svm_accuracy:.2f}")
print(f"LR Accuracy {lr_accuracy:.2f}")
print(f"RF Accuracy: {rf_accuracy:.2f}")
print(f"DT Accuracy: {dt_accuracy:.2f}")
print(f"KNN Accuracy: {knn_accuracy:.2f}")

--- Classification Result ---
SVM Accuracy: 0.77
LR Accuracy 0.80
RF Accuracy: 0.82
DT Accuracy: 0.72
KNN Accuracy: 0.76
