# ML Classification

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt

df = pd.read_csv("/Users/minsu/Desktop/abalone.csv", index_col=0)
df

Sex  Length  Diameter  Height  Whole_weight  Shucked_weight  \
id                                                                 
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   
...   ..     ...       ...     ...           ...             ...   
4172   F   0.565     0.450   0.165        0.8870          0.3700   
4173   M   0.590     0.440   0.135        0.9660          0.4390   
4174   M   0.600     0.475   0.205        1.1760          0.5255   
4175   F   0.625     0.485   0.150        1.0945          0.5310   
4176   M   0.710     0.555   0.195        1.9485          0.9455   

      Viscera_weight  Shell_weight  Rings  
id                                         
0             0.1010        0.1500     15  
1             0.0485        0.0700      7  
2             0.1415        0.2100      9  
3             0.1140        0.1550     10  
4             0.0395        0.0550      7  
...              ...           ...    ...  
4172          0.2390        0.2490     11  
4173          0.2145        0.2605     10  
4174          0.2875        0.3080      9  
4175          0.2610        0.2960     10  
4176          0.3765        0.4950     12  

[4177 rows x 9 columns]

## 데이터 전처리

In [38]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# 성별(범주형)을 수치형으로 변환
le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])

In [40]:
X = df.drop(['Rings'], axis=1)
X.head()

Sex  Length  Diameter  Height  Whole_weight  Shucked_weight  \
id                                                                
0     2   0.455     0.365   0.095        0.5140          0.2245   
1     2   0.350     0.265   0.090        0.2255          0.0995   
2     0   0.530     0.420   0.135        0.6770          0.2565   
3     2   0.440     0.365   0.125        0.5160          0.2155   
4     1   0.330     0.255   0.080        0.2050          0.0895   

    Viscera_weight  Shell_weight Age_Category  
id                                             
0           0.1010         0.150          Old  
1           0.0485         0.070        Young  
2           0.1415         0.210       Middle  
3           0.1140         0.155       Middle  
4           0.0395         0.055        Young

In [42]:
y = df['Rings']
y.head()

id
0    15
1     7
2     9
3    10
4     7
Name: Rings, dtype: int64

In [44]:
y.value_counts()

Rings
9     689
10    634
8     568
11    487
7     391
12    267
6     259
13    203
14    126
5     115
15    103
16     67
17     58
4      57
18     42
19     32
20     26
3      15
21     14
23      9
22      6
27      2
24      2
1       1
26      1
29      1
2       1
25      1
Name: count, dtype: int64

## 범주형 데이터 생성

In [47]:
# 3개의 범주로 나눔(젊은, 중간, 늙음)
df['Age_Category'] = pd.cut(df['Rings'], bins=[0, 8, 13, float('inf')], labels=['Young', 'Middle', 'Old'])

X = df.drop(['Rings', 'Age_Category'], axis=1)
y = df['Age_Category']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [49]:
X

Sex  Length  Diameter  Height  Whole_weight  Shucked_weight  \
id                                                                  
0       2   0.455     0.365   0.095        0.5140          0.2245   
1       2   0.350     0.265   0.090        0.2255          0.0995   
2       0   0.530     0.420   0.135        0.6770          0.2565   
3       2   0.440     0.365   0.125        0.5160          0.2155   
4       1   0.330     0.255   0.080        0.2050          0.0895   
...   ...     ...       ...     ...           ...             ...   
4172    0   0.565     0.450   0.165        0.8870          0.3700   
4173    2   0.590     0.440   0.135        0.9660          0.4390   
4174    2   0.600     0.475   0.205        1.1760          0.5255   
4175    0   0.625     0.485   0.150        1.0945          0.5310   
4176    2   0.710     0.555   0.195        1.9485          0.9455   

      Viscera_weight  Shell_weight  
id                                  
0             0.1010        0.1500  
1             0.0485        0.0700  
2             0.1415        0.2100  
3             0.1140        0.1550  
4             0.0395        0.0550  
...              ...           ...  
4172          0.2390        0.2490  
4173          0.2145        0.2605  
4174          0.2875        0.3080  
4175          0.2610        0.2960  
4176          0.3765        0.4950  

[4177 rows x 8 columns]

In [51]:
y

id
0          Old
1        Young
2       Middle
3       Middle
4        Young
         ...  
4172    Middle
4173    Middle
4174    Middle
4175    Middle
4176    Middle
Name: Age_Category, Length: 4177, dtype: category
Categories (3, object): ['Young' < 'Middle' < 'Old']

In [53]:
y.value_counts()

Age_Category
Middle    2280
Young     1407
Old        490
Name: count, dtype: int64

In [69]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, classification_report

In [121]:
print("---- ML SVM CLF Model -----")

---- ML SVM CLF Model -----


In [83]:
clf_svm = SVC(random_state=42)
clf_svm.fit(X_train, y_train)

y_pred_svm = clf_svm.predict(X_test)
svm_accuracy = accuracy_score(y_test, y_pred_svm)

print(f"ACC SVM RFC: {svm_accuracy:.2f}\n")
print(classification_report(y_test, y_pred_svm))
print(confusion_matrix(y_test, y_pred_svm))

ACC SVM RFC: 0.72

              precision    recall  f1-score   support

      Middle       0.69      0.91      0.78       456
         Old       1.00      0.01      0.02       101
       Young       0.82      0.67      0.74       279

    accuracy                           0.72       836
   macro avg       0.84      0.53      0.51       836
weighted avg       0.77      0.72      0.68       836

[[417   0  39]
 [ 99   1   1]
 [ 92   0 187]]


In [101]:
print("---- LogisticRegression CLF----")

---- LogisticRegression CLF----


In [87]:
lr_clf_model = LogisticRegression(random_state=42)
lr_clf_model.fit(X_train, y_train)

y_pred_lr = lr_clf_model.predict(X_test)

In [93]:
lr_acc = accuracy_score(y_test, y_pred_lr)

print(f"\nACC LR: {lr_acc:.2f}\n")
print(classification_report(y_test, y_pred_lr))
print(confusion_matrix(y_test, y_pred_lr))


ACC LR: 0.71

              precision    recall  f1-score   support

      Middle       0.70      0.84      0.76       456
         Old       0.82      0.14      0.24       101
       Young       0.74      0.71      0.72       279

    accuracy                           0.71       836
   macro avg       0.75      0.56      0.57       836
weighted avg       0.72      0.71      0.68       836

[[383   3  70]
 [ 86  14   1]
 [ 82   0 197]]


In [97]:
print("\n---- RF CLF ----\n")


---- RF CLF ----



In [107]:
from sklearn.ensemble import RandomForestClassifier

rf_clf_model = RandomForestClassifier(random_state=42)
rf_clf_model.fit(X_train, y_train)

y_pred_rf = rf_clf_model.predict(X_test)

In [111]:
rf_acc = accuracy_score(y_test, y_pred_rf)

print(f"\nACC RF: {rf_acc:.2f}\n")
print(classification_report(y_test, y_pred_rf))
print(confusion_matrix(y_test, y_pred_rf))


ACC RF: 0.73

              precision    recall  f1-score   support

      Middle       0.72      0.86      0.78       456
         Old       0.66      0.23      0.34       101
       Young       0.79      0.72      0.75       279

    accuracy                           0.73       836
   macro avg       0.72      0.60      0.62       836
weighted avg       0.73      0.73      0.72       836

[[390  12  54]
 [ 77  23   1]
 [ 78   0 201]]


In [113]:
print("\n---- DT CLF -----\n")


---- DT CLF -----



In [115]:
from sklearn.tree import DecisionTreeClassifier

In [117]:
dt_clf_model = DecisionTreeClassifier(random_state=42)
dt_clf_model.fit(X_train, y_train)

y_pred_dt = dt_clf_model.predict(X_test)

dt_acc = accuracy_score(y_test, y_pred_dt)

In [119]:
print(f"\nDT ACC: {dt_acc:.2f}\n")
print(classification_report(y_test, y_pred_dt))
print(confusion_matrix(y_test, y_pred_dt))


DT ACC: 0.64

              precision    recall  f1-score   support

      Middle       0.69      0.67      0.68       456
         Old       0.35      0.38      0.36       101
       Young       0.68      0.69      0.68       279

    accuracy                           0.64       836
   macro avg       0.57      0.58      0.58       836
weighted avg       0.65      0.64      0.65       836

[[307  61  88]
 [ 59  38   4]
 [ 76  10 193]]


In [123]:
print("\n---- KNN CLF ----\n")


---- KNN CLF ----



In [133]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf_model = KNeighborsClassifier()
knn_clf_model.fit(X_train, y_train)

y_pred_knn = knn_clf_model.predict(X_test)

knn_acc = accuracy_score(y_test, y_pred_knn)

In [135]:
print(f"\nKNN ACC: {knn_acc:.2f}\n")
print(classification_report(y_test, y_pred_knn))
print(confusion_matrix(y_test, y_pred_knn))


KNN ACC: 0.73

              precision    recall  f1-score   support

      Middle       0.72      0.83      0.77       456
         Old       0.65      0.32      0.43       101
       Young       0.77      0.71      0.74       279

    accuracy                           0.73       836
   macro avg       0.71      0.62      0.65       836
weighted avg       0.73      0.73      0.72       836

[[380  15  61]
 [ 69  32   0]
 [ 78   2 199]]


In [141]:
print(f"ACC SVM RFC: {svm_accuracy:.2f}\n")
print(classification_report(y_test, y_pred_svm))
print(confusion_matrix(y_test, y_pred_svm))
print("------------------------------------------")
print(f"\nACC LR: {lr_acc:.2f}\n")
print(classification_report(y_test, y_pred_lr))
print(confusion_matrix(y_test, y_pred_lr))
print("------------------------------------------")
print(f"\nACC RF: {rf_acc:.2f}\n")
print(classification_report(y_test, y_pred_rf))
print(confusion_matrix(y_test, y_pred_rf))
print("------------------------------------------")
print(f"\nDT ACC: {dt_acc:.2f}\n")
print(classification_report(y_test, y_pred_dt))
print(confusion_matrix(y_test, y_pred_dt))
print("------------------------------------------")
print(f"\nKNN ACC: {knn_acc:.2f}\n")
print(classification_report(y_test, y_pred_knn))
print(confusion_matrix(y_test, y_pred_knn))

ACC SVM RFC: 0.72

              precision    recall  f1-score   support

      Middle       0.69      0.91      0.78       456
         Old       1.00      0.01      0.02       101
       Young       0.82      0.67      0.74       279

    accuracy                           0.72       836
   macro avg       0.84      0.53      0.51       836
weighted avg       0.77      0.72      0.68       836

[[417   0  39]
 [ 99   1   1]
 [ 92   0 187]]
------------------------------------------

ACC LR: 0.71

              precision    recall  f1-score   support

      Middle       0.70      0.84      0.76       456
         Old       0.82      0.14      0.24       101
       Young       0.74      0.71      0.72       279

    accuracy                           0.71       836
   macro avg       0.75      0.56      0.57       836
weighted avg       0.72      0.71      0.68       836

[[383   3  70]
 [ 86  14   1]
 [ 82   0 197]]
------------------------------------------

ACC RF: 0.73

           